baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
[[module.imports]]
path = "github.com/halogenica/beautifulhugo"

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 3

[[menu.main]]
    parent = "projects"
    name = "Project 1"
    url = "projects/project-1"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "Project 2"
    url = "projects/project-2"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "Project 3"
    url = "projects/project-3"
    weight = 3